In [1]:
from protossl.datasets import HeedbECGDataset
from protossl.defines import HEEDB_TARGETS
from omegaconf import OmegaConf
from pathlib import Path
import numpy as np
import pandas as pd
from sklearn.metrics import roc_curve, balanced_accuracy_score, roc_auc_score

dataset_path = "/opt/gpudata/ecg/heedb"
arms = ["2D-partial", "2D-global", "1D-global"]
run_path = Path("/opt/gpu_working/steven/protoecgnet-heedb-v3")
config_path = Path("/opt/gpu_working/steven/ProtoSSL/large-user-study/configs")
fusion_path = run_path / "fusion/train-fusion-classifier/latest"
fusion_labels = list(HEEDB_TARGETS)
label_idxs = np.arange(len(HEEDB_TARGETS))

In [2]:
def stack_branched_arms():
    arm_labels = [l for arm in arms for l in OmegaConf.load(config_path / f"{arm}.yaml").data.init_args.label_subset]
    idxs = np.asarray([arm_labels.index(l) for l in fusion_labels]) # indices to normalize to fusion order

    ret = dict()
    for split in ["val", "test"] :
        arm_probs = {arm: np.load(run_path / arm / f"train-classifier/latest/{split}_probs.npy") for arm in arms}
        stacked_probs = np.concat([arm_probs[arm] for arm in arms], axis=1)
        ret[split] = stacked_probs[:, idxs]
    return ret

In [3]:
ds_phys = HeedbECGDataset(
    dataset_path=dataset_path,
    split="test",
    sampling_rate=100,
    label_src="original_physician",
    heedb_split_type="by-label",
    drop_blank_overread=True,
)

ds_phys_val = HeedbECGDataset(
    dataset_path=dataset_path,
    split="val",
    sampling_rate=100,
    label_src="original_physician",
    heedb_split_type="by-label",
    drop_blank_overread=True,
)

ds_muse = HeedbECGDataset(
    dataset_path=dataset_path,
    split="test",
    sampling_rate=100,
    label_src="original_muse",
    heedb_split_type="by-label",
    drop_blank_overread=True,
)

================get_heedb_metadata=================
using by-label splits
reading HEEDB metadata from on-disk cache: /home/songs1/.cache/protossl_cache/abac20ad.csv
===================================================
==============get_heedb_overread_mask==============
reading HEEDB overread mask from on-disk cache: /home/songs1/.cache/protossl_cache/22bb7f8c.npy
replaying below stats from cache:
Of 455748 ECGs, keeping 362090 with a physician overread, dropping 93658 with a blank overread and 0 not found in the diagnoses table
===================================================
=================make_heedb_labels=================
reading HEEDB labels from on-disk cache: /home/songs1/.cache/protossl_cache/02945b1e.npy
replaying below stats from cache:
Of 362090 ECGs and 11607259 annotations, 362090 matched (0 ECG annotations were missing and filled with 0s)
===================================================
===============StreamingECGWaveforms===============
Using streaming ECG waveforms, will load and transform data on the fly
===================================================
==============get_heedb_overread_mask==============
reading HEEDB overread mask from on-disk cache: /home/songs1/.cache/protossl_cache/fc58b37a.npy
replaying below stats from cache:
Of 451310 ECGs, keeping 359445 with a physician overread, dropping 91864 with a blank overread and 1 not found in the diagnoses table
===================================================
=================make_heedb_labels=================
reading HEEDB labels from on-disk cache: /home/songs1/.cache/protossl_cache/3cdccfd7.npy
replaying below stats from cache:
Of 359445 ECGs and 11607259 annotations, 359445 matched (0 ECG annotations were missing and filled with 0s)
===================================================
===============StreamingECGWaveforms===============
Using streaming ECG waveforms, will load and transform data on the fly
===================================================
==============get_heedb_overread_mask==============
reading HEEDB overread mask from on-disk cache: /home/songs1/.cache/protossl_cache/22bb7f8c.npy
replaying below stats from cache:
Of 455748 ECGs, keeping 362090 with a physician overread, dropping 93658 with a blank overread and 0 not found in the diagnoses table
===================================================
=================make_heedb_labels=================
reading HEEDB labels from on-disk cache: /home/songs1/.cache/protossl_cache/a835dab0.npy
replaying below stats from cache:
Of 362090 ECGs and 11607259 annotations, 362090 matched (0 ECG annotations were missing and filled with 0s)
===================================================
===============StreamingECGWaveforms===============
Using streaming ECG waveforms, will load and transform data on the fly
===================================================

In [4]:
y_true = ds_phys.labels.numpy()[:, label_idxs]
y_true_val = ds_phys_val.labels.numpy()[:, label_idxs]
y_pred_muse = ds_muse.labels.numpy()[:, label_idxs]

In [5]:
def compute_threshold(_y_true, _y_prob):
    # NOTE: should be computed on either train/val set, NOT test
    fpr, tpr, thresholds = roc_curve(_y_true, _y_prob)
    j_scores = tpr - fpr
    optimal_idx = np.argmax(j_scores)
    optimal_threshold = thresholds[optimal_idx]
    return optimal_threshold

In [6]:
temp = stack_branched_arms()
y_prob_branched, y_prob_branched_val = temp["test"], temp["val"]
y_prob_fusion = np.load(fusion_path / "test_probs.npy")
y_prob_fusion_val = np.load(fusion_path / "val_probs.npy")
assert y_prob_fusion.shape[1] == len(fusion_labels)

y_pred_branched = np.zeros_like(y_pred_muse)
y_pred_fusion = np.zeros_like(y_pred_muse)
accuracy_results = []
roc_results = []
for i, label in enumerate(fusion_labels):
    branched_threshold = compute_threshold(y_true_val[:, i], y_prob_branched_val[:, i])
    y_pred_branched[:, i] = (y_prob_branched[:, i] > branched_threshold).astype(int)
    fusion_threshold = compute_threshold(y_true_val[:, i], y_prob_fusion_val[:, i])
    y_pred_fusion[:, i] = (y_prob_fusion[:, i] > fusion_threshold).astype(int)
    label_acc_results = {
        "label": label,
        "muse: BalAcc": balanced_accuracy_score(y_true[:, i], y_pred_muse[:, i]),
        "branched: BalAcc": balanced_accuracy_score(y_true[:, i], y_pred_branched[:, i]),
        "fusion: BalAcc": balanced_accuracy_score(y_true[:, i], y_pred_fusion[:, i]),
    }
    label_roc_results = {
        "label": label,
        # NOTE: can't compute muse roc given no probs
        "branched: AUROC": roc_auc_score(y_true[:, i], y_prob_branched[:, i]),
        "fusion: AUROC": roc_auc_score(y_true[:, i], y_prob_fusion[:, i]),
    }
    accuracy_results.append(label_acc_results)
    roc_results.append(label_roc_results)

In [7]:
roc_df = pd.DataFrame(roc_results)
idx = len(roc_df)
roc_df.loc[idx, "label"] = "Macro Average"
for c in [c for c in roc_df.columns if c != "label"]:
    roc_df.loc[idx, c] = roc_df[c].mean()

with pd.option_context("display.precision", 3):
    display(roc_df)

                                   label  branched: AUROC  fusion: AUROC
0                       ANTERIOR INFARCT            0.951          0.951
1                    ATRIAL FIBRILLATION            0.970          0.970
2                         ATRIAL FLUTTER            0.957          0.957
3                    ATRIAL-PACED RHYTHM            0.984          0.984
4   INCOMPLETE RIGHT BUNDLE BRANCH BLOCK            0.966          0.965
5                       INFERIOR INFARCT            0.972          0.972
6                        LATERAL INFARCT            0.954          0.953
7               LEFT BUNDLE BRANCH BLOCK            0.988          0.987
8                    NORMAL SINUS RHYTHM            0.959          0.959
9             PREMATURE ATRIAL COMPLEXES            0.905          0.913
10       PREMATURE VENTRICULAR COMPLEXES            0.901          0.900
11                  RIGHT AXIS DEVIATION            0.986          0.985
12             RIGHT BUNDLE BRANCH BLOCK            0.991          0.991
13                     SINUS BRADYCARDIA            0.988          0.988
14                          SINUS RHYTHM            0.849          0.853
15                     SINUS TACHYCARDIA            0.989          0.989
16               VENTRICULAR TACHYCARDIA            0.871          0.872
17              VENTRICULAR-PACED RHYTHM            0.984          0.984
18              WITH 1ST DEGREE AV BLOCK            0.981          0.980
19                 WITH SINUS ARRHYTHMIA            0.972          0.971
20                         Macro Average            0.956          0.956

In [8]:
acc_df = pd.DataFrame(accuracy_results)
idx = len(acc_df)
acc_df.loc[idx, "label"] = "Macro Average"
for c in [c for c in acc_df.columns if c != "label"]:
    acc_df.loc[idx, c] = acc_df[c].mean()

with pd.option_context("display.precision", 3):
    display(acc_df)

,label,muse: BalAcc,branched: BalAcc,fusion: BalAcc
0,ANTERIOR INFARCT,0.950,0.891,0.890
1,ATRIAL FIBRILLATION,0.933,0.918,0.918
2,ATRIAL FLUTTER,0.851,0.895,0.894
3,ATRIAL-PACED RHYTHM,0.846,0.942,0.944
4,INCOMPLETE RIGHT BUNDLE BRANCH BLOCK,0.907,0.911,0.911
5,INFERIOR INFARCT,0.975,0.912,0.912
6,LATERAL INFARCT,0.973,0.909,0.907
7,LEFT BUNDLE BRANCH BLOCK,0.939,0.958,0.958
8,NORMAL SINUS RHYTHM,0.938,0.910,0.910
9,PREMATURE ATRIAL COMPLEXES,0.911,0.838,0.850
10,PREMATURE VENTRICULAR COMPLEXES,0.935,0.836,0.835
11,RIGHT AXIS DEVIATION,0.911,0.958,0.957
12,RIGHT BUNDLE BRANCH BLOCK,0.978,0.971,0.970
13,SINUS BRADYCARDIA,0.968,0.968,0.968
14,SINUS RHYTHM,0.867,0.770,0.772
15,SINUS TACHYCARDIA,0.968,0.965,0.965
16,VENTRICULAR TACHYCARDIA,0.655,0.788,0.790
17,VENTRICULAR-PACED RHYTHM,0.746,0.948,0.949
18,WITH 1ST DEGREE AV BLOCK,0.966,0.941,0.941
19,WITH SINUS ARRHYTHMIA,0.957,0.931,0.929
20,Macro Average,0.909,0.908,0.909